name: Deploy

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set context to repo
              uses: actions/checkout@v4
            
            - name: Create bin directory
              run: mkdir -p bin
            
            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                java-version: '25'
                distribution: 'temurin'
            
            - name: Compile
              run: javac -d bin ims/*.java
              
            - name: Package into a JAR
              run: jar cmvf MANIFEST.MF IMS.jar -C bin .
              
            - name: Verify JAR
              run: ls -la *.jar
              
            - name: Release build
              uses: softprops/action-gh-release@v1
              with:
                name: Release ${{ github.ref_name }}
                files: IMS.jar
                body: |
                    # Inventory Management System
                    
                    ## Default credentials
                    | Field | Value |
                    |---|---|
                    | Username | test |
                    | Password | 4567 |
                    
                    ## How to Run?
                    Double-click `IMS.jar`. `IMS.jar` is within the `zip` file that you can download below.
                    
                    Alternatively, you can run...
                    ```
                        java -jar IMS.jar
                    ```
                    on your local `cmd.exe`.